export const markdownTestCases = {
  mathInline: 'Inline math: $E = mc^2$ in a sentence.',
  mathBlock: 'Block math:\n\n$$\\sum_{i=1}^n x_i$$\n',
  gfmTable: '| Name | Value |\n| --- | --- |\n| Alpha | 1 |\n| Beta | 2 |',
  checklist: '- [ ] Todo\n- [x] Done',
  wikiLinks: '[[PageName]] and [[PageName|Display Text]]',
  htmlEntities: 'Hello &amp; &quot;World&quot;',
  frontmatter: '---\ntitle: Test\ntags: [a, b]\n---\nBody text',
  codeBlock: '```js\nconst answer = 42;\nconsole.log(answer);\n```',
  mixedContent: [
    '---',
    'title: Mixed Document',
    'tags: [math, tables, links]',
    '---',
    '',
    'Inline math: $E = mc^2$',
    '',
    '$$\\sum_{i=1}^n x_i$$',
    '',
    '| Name | Value |',
    '| --- | --- |',
    '| Alpha | 1 |',
    '| Beta | 2 |',
    '',
    '- [ ] Todo',
    '- [x] Done',
    '',
    '[[PageName]] and [[PageName|Display Text]]',
    '',
    'Hello &amp; &quot;World&quot;',
    '',
    '```js',
    'const answer = 42;',
    'console.log(answer);',
    '```',
    '',
    '<span>HTML content</span>',
  ].join('\n'),
};
