//! Android CA store configuration for the git2 engine.
//!
//! Android's system CA certificates live in one of two locations:
//! - **`/apex/com.android.conscrypt/cacerts`** (Android 10+, preferred — unified
//!   CA store managed by the Conscrypt APEX module)
//! - **`/system/etc/security/cacerts`** (legacy path, present on some devices)
//!
//! Both directories contain hash-named PEM-encoded root CA certificates
//! used to verify TLS server certificates. The Rust git2 engine (via OpenSSL's
//! `SSL_CTX_load_verify_locations` file mode) needs a PEM bundle file on Android
//! because the vendored OpenSSL build does not auto-detect the Android paths, and
//! the hash-based filename convention used by Android is incompatible with
//! OpenSSL's directory-mode expectations.
//!
//! ## Architecture
//!
//! The Kotlin host (`GitEngineModule`) is responsible for building the PEM bundle:
//!   1. It reads all readable PEM files from the Android CA directories.
//!   2. It concatenates them into a single bundle file in app-private storage,
//!      written atomically (temp file + rename) and cached (skipped if already
//!      present and non-empty).
//!   3. It passes the bundle path to `set_ssl_cert_file()` via UniFFI.
//!
//! Rust (`set_ssl_cert_file`) then configures libgit2's OpenSSL adapter:
//!   - Calls `git2::opts::set_ssl_cert_file` with the bundle path.
//!
//! ## Safety contract
//!
//! `git2::opts::set_ssl_cert_file` **mutates a C global** inside libgit2's OpenSSL
//! adapter. The C global is process-local state, not thread-local. Calling it while
//! another thread is inside a git operation is a data race. The Kotlin `OnCreate`
//! lifecycle callback runs on the main thread **before** any async engine ops can
//! be dispatched, so we invoke it there — before the React Native JS thread has
//! posted any engine work. This is the single allowed call site; no other call
//! may be added.
//!
//! ## No certificate bypass
//!
//! `set_ssl_cert_file` directs OpenSSL to the Android CA bundle; it does not
//! disable verification. GitHub's TLS certificate remains validated against
//! trusted system CAs.

use std::path::{Path, PathBuf};

/// Errors that can occur when configuring the Android CA store.
#[derive(Debug, thiserror::Error)]
pub enum AndroidCaError {
    #[error("failed to set SSL certificate file: {0}")]
    SetCertFile(#[from] git2::Error),
    #[error("certificate file is not readable: {0}")]
    NotReadable(#[from] std::io::Error),
}

/// Configure git2's SSL certificate file for Android.
///
/// This function must be called **once** from the Kotlin `OnCreate` lifecycle
/// callback — before any engine operation (clone/fetch/push/pull) is dispatched.
///
/// # Safety
///
/// `git2::opts::set_ssl_cert_file` writes to a **C global** inside libgit2's
/// OpenSSL adapter. The global is process-local. Calling this concurrently
/// from multiple threads while git ops are in-flight is undefined behaviour.
/// The single call in `GitEngineModule.OnCreate` on the main thread, before any
/// engine work is posted, satisfies the thread-safety requirement.
///
/// # Arguments
///
/// * `cert_file` - Path to a PEM file containing concatenated root CA
///   certificates. On Android this is generated by the Kotlin host from the
///   system CA directories.
pub fn set_ssl_cert_file(cert_file: &Path) -> Result<(), AndroidCaError> {
    // Validate the file is readable before passing it to git2.
    if !cert_file.is_file() {
        return Err(AndroidCaError::NotReadable(std::io::Error::new(
            std::io::ErrorKind::NotFound,
            "certificate file not found",
        )));
    }

    // SAFETY: This function must only be called from the main thread before
    // any git2 operations begin. The caller is `GitEngineModule.OnCreate` in
    // the Kotlin Expo module, which runs on the Android main thread before
    // any async engine operations are posted to the JS queue. No other thread
    // can be inside a git2 call at this point. The C global mutated by
    // `set_ssl_cert_file` is process-local (not thread-local), so this single
    // serialized call from the main thread has well-defined behaviour.
    //
    // The library global is not accessed again until the first engine
    // operation is dispatched, which always happens after this call completes.
    unsafe {
        git2::opts::set_ssl_cert_file(cert_file.to_string_lossy().as_ref())?;
    }
    Ok(())
}

pub fn set_ssl_cert_directory(cert_dir: &Path) -> Result<(), AndroidCaError> {
    if !cert_dir.is_dir() {
        return Err(AndroidCaError::NotReadable(std::io::Error::new(
            std::io::ErrorKind::NotFound,
            "certificate directory not found",
        )));
    }

    // SAFETY: Same contract as `set_ssl_cert_file` — single main-thread call
    // before any engine operations.
    unsafe {
        git2::opts::set_ssl_cert_dir(cert_dir.to_string_lossy().as_ref())?;
    }
    Ok(())
}

/// Returns the best available Android CA certificate directory.
///
/// Prefers the APEX path (`/apex/com.android.conscrypt/cacerts`) when it
/// exists; falls back to the legacy path (`/system/etc/security/cacerts`) only
/// if the APEX path does not exist. Returns `None` when neither path is
/// available (i.e., not on Android).
///
/// `apex_override` and `legacy_override` exist solely for deterministic unit
/// testing; pass `None` in production to use the hardcoded defaults.
pub fn android_ca_dir(
    apex_override: Option<&Path>,
    legacy_override: Option<&Path>,
) -> Option<PathBuf> {
    const ANDROID_CA_APEX_DEFAULT: &str = "/apex/com.android.conscrypt/cacerts";
    const ANDROID_CA_LEGACY_DEFAULT: &str = "/system/etc/security/cacerts";

    let apex = apex_override.unwrap_or_else(|| Path::new(ANDROID_CA_APEX_DEFAULT));
    let legacy = legacy_override.unwrap_or_else(|| Path::new(ANDROID_CA_LEGACY_DEFAULT));

    if apex.exists() {
        return Some(apex.to_path_buf());
    }
    if legacy.exists() {
        return Some(legacy.to_path_buf());
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Unique counter for test directory isolation.
    static TEST_DIR_COUNTER: std::sync::atomic::AtomicU32 = std::sync::atomic::AtomicU32::new(0);

    /// Returns a unique temporary directory path, creating it.
    /// The directory is NOT auto-deleted; tests must clean it up.
    fn unique_temp_dir() -> std::path::PathBuf {
        let n = TEST_DIR_COUNTER.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
        let dir = std::env::temp_dir().join(format!("gitnotes_android_ca_test_{n}"));
        std::fs::create_dir_all(&dir).expect("temp dir creation");
        dir
    }

    /// Cleans up a temp directory created by `unique_temp_dir`.
    fn cleanup_temp_dir(dir: &Path) {
        let _ = std::fs::remove_dir_all(dir);
    }

    #[test]
    fn android_ca_dir_prefers_apex_over_legacy() {
        let td = unique_temp_dir();
        let apex = td.join("apex_cacerts");
        let legacy = td.join("legacy_cacerts");
        std::fs::create_dir(&apex).unwrap();
        std::fs::create_dir(&legacy).unwrap();

        let result = android_ca_dir(Some(apex.as_path()), Some(legacy.as_path()));
        assert_eq!(result.as_ref(), Some(&apex));
        cleanup_temp_dir(&td);
    }

    #[test]
    fn android_ca_dir_falls_back_to_legacy_when_apex_absent() {
        let td = unique_temp_dir();
        let legacy = td.join("legacy_cacerts");
        std::fs::create_dir(&legacy).unwrap();

        let result = android_ca_dir(None, Some(legacy.as_path()));
        assert_eq!(result.as_ref(), Some(&legacy));
        cleanup_temp_dir(&td);
    }

    #[test]
    fn android_ca_dir_returns_none_when_neither_exists() {
        let td = unique_temp_dir();
        let result = android_ca_dir(
            Some(td.join("nonexistent_apex").as_path()),
            Some(td.join("nonexistent_legacy").as_path()),
        );
        assert!(result.is_none());
        cleanup_temp_dir(&td);
    }

    #[test]
    fn android_ca_dir_returns_apex_when_only_apex_exists() {
        let td = unique_temp_dir();
        let apex = td.join("apex_cacerts");
        std::fs::create_dir(&apex).unwrap();

        let result = android_ca_dir(Some(apex.as_path()), None);
        assert!(result.is_some());
        assert_eq!(result.unwrap(), apex);
        cleanup_temp_dir(&td);
    }

    #[test]
    fn android_ca_dir_handles_real_android_paths_without_panic() {
        let apex = Path::new("/apex/com.android.conscrypt/cacerts");
        let legacy = Path::new("/system/etc/security/cacerts");
        let (apex_exists, legacy_exists) = (apex.exists(), legacy.exists());
        let result = android_ca_dir(None, None);
        // Result must be consistent: if neither path exists, result must be None
        if !apex_exists && !legacy_exists {
            assert!(result.is_none());
        }
    }

    #[test]
    fn set_ssl_cert_file_rejects_nonexistent_file() {
        let td = unique_temp_dir();
        let nonexistent = td.join("nonexistent.pem");

        let result = set_ssl_cert_file(&nonexistent);
        // SAFETY: called with non-existent path; will fail before any git2 op.
        assert!(result.is_err());
        // Error should be NotReadable (file not found)
        assert!(matches!(result, Err(AndroidCaError::NotReadable(_))));
        cleanup_temp_dir(&td);
    }

    #[test]
    fn set_ssl_cert_file_rejects_directory() {
        let td = unique_temp_dir();
        let result = set_ssl_cert_file(&td);
        assert!(result.is_err());
        cleanup_temp_dir(&td);
    }
}
