/**
 * Config plugin: force git smart-HTTP traffic off HTTP/3 (QUIC).
 *
 * Some networks black-hole UDP/443 (QUIC) to specific GitHub edge IPs, so
 * URLSession's QUIC connection stalls forever while TCP (HTTP/2, HTTP/1.1)
 * completes instantly. iOS 26 ignores `assumesHTTP3Capable = false` on the
 * request, so this plugin injects a custom URLProtocol into AppDelegate that
 * intercepts github.com git endpoints and re-issues them over an ephemeral
 * HTTP/1.1 session (no pooled QUIC route).
 *
 * The `ios/` native project is generated by `expo prebuild`, so the injection
 * must happen at prebuild time — editing AppDelegate directly is wiped on the
 * next prebuild.
 */
const { withAppDelegate, withInfoPlist } = require('@expo/config-plugins');

const GIT_HTTP11_PROTOCOL_SWIFT = `
final class GitHttp11URLProtocol: URLProtocol {
  private var urlTask: URLSessionDataTask?
  private static let isRelevant: (URLRequest) -> Bool = { request in
    guard let url = request.url, url.host == "github.com" else { return false }
    return url.path.contains(".git/") || url.path.hasSuffix(".git")
  }

  override class func canInit(with request: URLRequest) -> Bool {
    isRelevant(request)
  }

  override class func canonicalRequest(for request: URLRequest) -> URLRequest {
    let mutable = (request as NSURLRequest).mutableCopy() as! NSMutableURLRequest
    if #available(iOS 14.5, *) {
      mutable.assumesHTTP3Capable = false
    }
    mutable.setValue("close", forHTTPHeaderField: "Connection")
    return mutable as URLRequest
  }

  override func startLoading() {
    let mutable = (request as NSURLRequest).mutableCopy() as! NSMutableURLRequest
    if #available(iOS 14.5, *) {
      mutable.assumesHTTP3Capable = false
    }
    mutable.setValue("close", forHTTPHeaderField: "Connection")
    let request = mutable as URLRequest
    let config = URLSessionConfiguration.ephemeral
    config.timeoutIntervalForRequest = 120
    config.timeoutIntervalForResource = 600
    let session = URLSession(configuration: config)
    urlTask = session.dataTask(with: request) { [weak self] data, response, error in
      guard let self else { return }
      if let error {
        self.client?.urlProtocol(self, didFailWithError: error)
        return
      }
      if let response {
        self.client?.urlProtocol(self, didReceive: response, cacheStoragePolicy: .notAllowed)
      }
      if let data {
        self.client?.urlProtocol(self, didLoad: data)
      }
      self.client?.urlProtocolDidFinishLoading(self)
    }
    urlTask?.resume()
  }

  override func stopLoading() {
    urlTask?.cancel()
    urlTask = nil
  }
}
`;

const GIT_HTTP11_HOOK = `
    // Force git smart-HTTP to github.com off QUIC (HTTP/3): some networks
    // black-hole UDP/443 to specific GitHub edge IPs, stalling the connection
    // forever while HTTP/1.1 completes. Injected by the git-quic-workaround
    // config plugin at prebuild time.
    ExpoFetchCustomExtension.setCustomURLSessionConfigurationProvider {
      let config = URLSessionConfiguration.default
      config.protocolClasses = [GitHttp11URLProtocol.self] + (config.protocolClasses ?? [])
      config.timeoutIntervalForRequest = 120
      config.timeoutIntervalForResource = 600
      return config
    }
`;

function withGitQuicWorkaround(config) {
  return withAppDelegate(config, (delegateConfig) => {
    const src = delegateConfig.modResults.contents;
    if (src.includes('GitHttp11URLProtocol')) return delegateConfig;

    // 1. Prepend the URLProtocol class right after the imports (before @main).
    const mainMarker = '@main\nclass AppDelegate';
    if (!src.includes(mainMarker)) {
      throw new Error(
        'git-quic-workaround: could not locate `@main class AppDelegate` in AppDelegate.swift',
      );
    }
    delegateConfig.modResults.contents = src.replace(
      mainMarker,
      `${GIT_HTTP11_PROTOCOL_SWIFT}\n\n${mainMarker}`,
    );

    // 2. Insert the session-config hook into didFinishLaunchingWithOptions,
    //    right before the iOS window setup.
    const hookAnchor = '#if os(iOS) || os(tvOS)';
    if (!src.includes(GIT_HTTP11_HOOK.trim())) {
      delegateConfig.modResults.contents = delegateConfig.modResults.contents.replace(
        hookAnchor,
        `${GIT_HTTP11_HOOK}\n${hookAnchor}`,
      );
    }

    return delegateConfig;
  });
}

module.exports = withGitQuicWorkaround;
