/**
 * Config plugin: add the Keychain Sharing entitlement to the iOS app.
 *
 * `expo-secure-store` stores values in the iOS keychain, which requires the
 * `keychain-access-groups` entitlement to be present in the signed app.
 * Without it, every read/write fails with:
 *
 *   KeyChainException: A required entitlement isn't present.
 *   (at ExpoSecureStore/SecureStoreModule.swift)
 *
 * Expo's own plugin only wires NSFaceIDUsageDescription + Android backup
 * rules — it does NOT add the keychain group. The `ios/` directory is
 * generated by `expo prebuild` (gitignored), so the entitlement must be
 * injected here at prebuild time.
 *
 * `$(AppIdentifierPrefix)` is resolved by Xcode at build time from the
 * signing team; `$(CFBundleIdentifier)` is the app's bundle id. On the
 * simulator (ad-hoc signing) this resolves to the simulator keychain group,
 * which is what SecureStore reads.
 */
const { withEntitlementsPlist } = require('@expo/config-plugins');

module.exports = function withKeychainAccessGroup(config) {
  return withEntitlementsPlist(config, (config) => {
    const existing = config.modResults['keychain-access-groups'];
    if (!Array.isArray(existing) || existing.length === 0) {
      config.modResults['keychain-access-groups'] = [
        '$(AppIdentifierPrefix)$(CFBundleIdentifier)',
      ];
    }
    return config;
  });
};
