[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["desktop"] }
dioxus-router = { workspace = true }
gn-core = { path = "../crates/gn-core" }
gn-github = { path = "../crates/gn-github" }
gn-parser = { path = "../crates/gn-parser" }
tracing-subscriber = { workspace = true }
