export type GitProgressKind =
  | 'Transfer'
  | 'Indexing'
  | 'Sideband'
  | 'Checkout'
  | 'Push'
  | 'Rebase'
  | 'Merge';

export interface GitProgressEvent {
  kind: GitProgressKind;
  text: string;
  received: number;
  indexed: number;
  total: number;
  percent: number;
}

export type FileStatusKind =
  | 'Unmodified'
  | 'Untracked'
  | 'Added'
  | 'Modified'
  | 'Deleted'
  | 'Renamed'
  | 'TypeChange'
  | 'Conflicted';

export type DiffLineOrigin =
  | 'Context'
  | 'Addition'
  | 'Deletion'
  | 'ContextEof'
  | 'AdditionEof'
  | 'DeletionEof';

export type PullKind =
  | 'UpToDate'
  | 'FastForward'
  | 'Merged'
  | 'Conflict'
  | 'Dirty'
  | 'NoUpstream'
  | 'Unborn';

export interface Author {
  name: string;
  email: string;
}

export interface HunkSelection {
  lineIndices: number[];
}

export interface RepoStatus {
  repoId: string;
  path: string;
  isRepo: boolean;
  currentBranch: string | null;
  ahead: number;
  behind: number;
  stagedCount: number;
  modifiedCount: number;
  untrackedCount: number;
  conflictedCount: number;
  isLocked: boolean;
  lastOpError: string | null;
}

export interface FileStatus {
  path: string;
  status: FileStatusKind;
  staged: boolean;
  conflicted: boolean;
  indexStatus: string;
  workdirStatus: string;
}

export interface DiffLine {
  index: number;
  origin: DiffLineOrigin;
  oldLineno: number | null;
  newLineno: number | null;
  content: string;
}

export interface FileDiff {
  path: string;
  status: FileStatusKind;
  isBinary: boolean;
  added: number;
  deleted: number;
  lines: DiffLine[];
}

export interface CommitInfo {
  id: string;
  shortId: string;
  message: string;
  summary: string;
  authorName: string;
  authorEmail: string;
  authorTime: number;
  committerTime: number;
  parentCount: number;
  parents: string[];
}

export interface ConflictEntry {
  path: string;
  ours: string | null;
  theirs: string | null;
  ancestor: string | null;
  status: string;
}

export interface PullResult {
  kind: PullKind;
  message: string;
  conflicts: ConflictEntry[];
}

export interface PushResult {
  pushed: boolean;
  nonFastForward: boolean;
  message: string;
}

export type PushIntegrateKind =
  | 'Direct'
  | 'Rebased'
  | 'Merged'
  | 'FastForward'
  | 'Conflicts'
  | 'None';

/** One conflicted file reported by push-with-integrate (stage-1/2/3 blob ids). */
export interface ConflictFile {
  path: string;
  base: string | null;
  ours: string | null;
  theirs: string | null;
}

/** Text content of the conflict stages for one conflicted file. `ours`/`theirs`
 * are empty strings when a stage is absent; binary content is rejected by the
 * engine as unsupported. */
export interface ConflictBlobs {
  path: string;
  base: string | null;
  ours: string;
  theirs: string;
}

/** Outcome of a push that transparently fetches + integrates on non-fast-forward. */
export interface PushIntegrateResult {
  pushed: boolean;
  integrated: boolean;
  kind: PushIntegrateKind;
  conflicts: ConflictFile[];
  message: string;
}

export interface BranchInfo {
  name: string;
  upstream: string | null;
  isCurrent: boolean;
  isRemote: boolean;
  ahead: number;
  behind: number;
}

export interface RemoteInfo {
  name: string;
  url: string | null;
  fetchSpecs: string[];
  pushSpecs: string[];
}

export interface RepoInfo {
  path: string;
  isRepo: boolean;
  currentBranch: string | null;
  headOid: string | null;
  remotes: string[];
  totalCommits: number;
  isClean: boolean;
}

export interface RepairReport {
  indexRebuilt: boolean;
  looseObjectsPruned: number;
  fetchHeadDeleted: boolean;
  repaired: string[];
  unrecoverable: string[];
  isHealthy: boolean;
}

/** Credential shape accepted by the native engine (maps 1:1 to UniFFI `CredentialSource`). */
export type NativeCredentialKind = 'userpass' | 'ssh' | 'default' | 'none';

export interface NativeCredential {
  kind: NativeCredentialKind;
  username?: string;
  password?: string;
  privateKey?: string;
  publicKey?: string | null;
  passphrase?: string | null;
}

/** SSH keypair generated by the Rust engine (ed25519 only). */
export interface GeneratedKey {
  publicKey: string;
  privateKey: string;
}

/** Error thrown by engine ops. `corruption` flags corrupt-repo failures so the
 * app can route them into the repair flow. */
export interface GitEngineError extends Error {
  corruption: boolean;
  code?: string;
}

export interface GitEngineModule {
  version(): Promise<string>;
  engineName(): Promise<string>;
  isRepoLocked(path: string): Promise<boolean>;
  setCredential(repoId: string, credential: NativeCredential): Promise<void>;
  getCredential(repoId: string): Promise<NativeCredential | null>;
  clearCredential(repoId: string): Promise<boolean>;
  generateSshKey(passphrase: string | null): Promise<GeneratedKey>;
  clone(url: string, dest: string, repoId?: string | null): Promise<string>;
  initRepo(path: string, bare: boolean): Promise<void>;
  removeRepo(path: string): Promise<void>;
  repoStatus(repoId: string, path: string): Promise<RepoStatus>;
  listStatuses(path: string): Promise<FileStatus[]>;
  diffAll(path: string): Promise<FileDiff[]>;
  diffFile(path: string, filePath: string): Promise<FileDiff>;
  stagePaths(path: string, paths: string[]): Promise<void>;
  unstagePaths(path: string, paths: string[]): Promise<void>;
  removePaths(path: string, paths: string[], keepWorktree: boolean): Promise<void>;
  discardFiles(path: string, paths: string[]): Promise<void>;
  stageFileLines(path: string, filePath: string, hunks: HunkSelection[]): Promise<void>;
  commit(path: string, message: string, authorName: string, authorEmail: string): Promise<CommitInfo>;
  recentCommits(path: string, limit: number): Promise<CommitInfo[]>;
  commitDiff(path: string, commitId: string): Promise<FileDiff[]>;
  checkoutCommit(path: string, commitId: string): Promise<void>;
  resetSoft(path: string, commitId: string): Promise<void>;
  revertCommit(path: string, commitId: string, authorName: string, authorEmail: string): Promise<CommitInfo>;
  getConflicts(path: string): Promise<ConflictEntry[]>;
  resolveConflict(path: string, filePath: string): Promise<void>;
  getConflictBlobs(path: string, filePath: string): Promise<ConflictBlobs>;
  markConflictResolved(path: string, filePath: string): Promise<void>;
  fetch(path: string, remoteName: string, repoId?: string | null): Promise<void>;
  pull(path: string, remoteName: string, repoId?: string | null): Promise<PullResult>;
  push(path: string, remoteName: string, repoId?: string | null, force?: boolean): Promise<PushResult>;
  pushWithIntegrate(path: string, remoteName: string, repoId?: string | null): Promise<PushIntegrateResult>;
  listBranches(path: string, remoteName: string): Promise<BranchInfo[]>;
  createBranch(path: string, name: string, source: string | null): Promise<BranchInfo>;
  checkoutBranch(path: string, name: string, remoteName: string): Promise<void>;
  deleteBranch(path: string, name: string): Promise<void>;
  renameBranch(path: string, name: string, newName: string): Promise<BranchInfo>;
  listRemotes(path: string): Promise<RemoteInfo[]>;
  addRemote(path: string, name: string, url: string): Promise<void>;
  removeRemote(path: string, name: string): Promise<void>;
  setRemoteUrl(path: string, name: string, url: string): Promise<void>;
  repoInfo(path: string): Promise<RepoInfo>;
  repairRepo(path: string): Promise<RepairReport>;
  backupCorruptRepo(path: string): Promise<string>;
}
