[toolchain]
channel = "stable"
components = ["rustfmt", "clippy"]
targets = [
  "aarch64-apple-ios",
  "aarch64-apple-ios-sim",
  "x86_64-apple-ios",
  "arm64-v8a-linux-android",
  "armeabi-v7a-linux-android",
  "x86_64-linux-android",
]
