import { Dimensions, StyleSheet } from 'react-native';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');

export const settingsStyles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { flex: 1 },
  section: { marginTop: 20, paddingHorizontal: 16, borderRadius: 12, marginHorizontal: 16 },
  sectionTitle: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase', paddingTop: 14, paddingBottom: 8, letterSpacing: 0.5 },
  settingItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 14, borderBottomWidth: StyleSheet.hairlineWidth },
  settingLabel: { fontSize: 16 },
  settingValue: { fontSize: 15 },
  settingLeft: { flexDirection: 'row', alignItems: 'center' },
  authUserRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  avatar: { width: 40, height: 40, borderRadius: 20 },
  addRepoButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 12, borderTopWidth: StyleSheet.hairlineWidth, gap: 6 },
  addRepoButtonText: { fontSize: 15, fontWeight: '600' },
  disabledButton: { opacity: 0.4 },
  emptyRepos: { paddingVertical: 24, alignItems: 'center', gap: 6 },
  emptyReposText: { fontSize: 15, fontWeight: '500' },
  repoItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, gap: 10 },
  repoName: { fontSize: 15, fontWeight: '500' },
  repoPath: { fontSize: 12 },
  repoInfo: { flex: 1 },
  syncButton: { padding: 8 },
  syncSpinner: { marginHorizontal: 8 },
  removeButton: { padding: 4 },
  repoSearchContainer: { paddingHorizontal: 16, paddingVertical: 8 },
  manualRepoRow: { flexDirection: 'row', alignItems: 'center', padding: 16, borderBottomWidth: 1, gap: 8 },
  manualRepoInput: { flex: 1, height: 40, borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, fontSize: 14 },
  manualAddBtn: { paddingHorizontal: 16, height: 40, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  manualAddBtnText: { color: '#fff', fontWeight: '600', fontSize: 14 },
  pickerSectionLabel: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5, paddingHorizontal: 16, paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth },
  pickerEmpty: { padding: 24, textAlign: 'center', fontSize: 14 },
  pickerItem: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: StyleSheet.hairlineWidth, gap: 12 },
  pickerItemInfo: { flex: 1 },
  pickerItemName: { fontSize: 15, fontWeight: '500' },
  pickerItemDesc: { fontSize: 13, marginTop: 2 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalSheet: { borderTopLeftRadius: 16, borderTopRightRadius: 16, paddingBottom: 34, maxHeight: SCREEN_HEIGHT * 0.75 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1 },
  modalTitle: { fontSize: 18, fontWeight: '600' },
  modalBody: { padding: 16 },
  modalDesc: { fontSize: 14, marginBottom: 12, lineHeight: 20 },
  generateLink: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 16 },
  generateLinkText: { fontSize: 14, fontWeight: '500' },
  tokenInputRow: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, marginBottom: 8, height: 50 },
  tokenInputInner: { flex: 1, fontSize: 14, paddingVertical: 0 },
  tokenIconBtn: { paddingHorizontal: 6, paddingVertical: 6, marginLeft: 4 },
  tokenActionsRow: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  tokenActionBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 10, paddingHorizontal: 12, borderRadius: 8, borderWidth: 1, flex: 1, gap: 6 },
  tokenActionLabel: { fontSize: 14, fontWeight: '600' },
  errorText: { color: '#FF3B30', fontSize: 13, marginBottom: 10 },
  modalButton: { paddingVertical: 14, borderRadius: 8, alignItems: 'center', marginTop: 8 },
  modalButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  bottomPad: { height: 40 },
  creditsWrap: { paddingTop: 24, marginHorizontal: -8, alignItems: 'center' },
  creditsText: { fontSize: 12, textAlign: 'center', lineHeight: 18 },
  credits: { fontSize: 12, textAlign: 'center', paddingHorizontal: 0, marginHorizontal: -8, paddingTop: 24, lineHeight: 18 },
});
